baseURL = 'https://abgelehnt.github.io/'
languageCode = 'zh-CN'
title = "Chi's Blog"
theme = ["PaperMod"]
uglyURLs = true
enableRobotsTXT = true

enableGitInfo = true
hasCJKLanguage = true

[taxonomies]
	tag = "tags"

[[menu.main]]
	name = "Archive"
	url = "archives.html"
	weight = 5
[[menu.main]]
	name = "Tags"
	url = "tags.html"
	weight = 10
[[menu.main]]
	name = "Search"
	url = "search.html"
	weight = 10

[params.homeInfoParams]
	Title = "Chi的个人博客"
	Content = "记录知识、分享知识"

[[params.socialIcons]]
	name = "email"
	url = "mailto:abgelehnt@foxmail.com"

[[params.socialIcons]]
	name = "github"
	url = "https://github.com/abgelehnt"

[params]
	author = "Chi Zhang"
	ShowReadingTime = true
	ShowWordCount = true
	ShowCodeCopyButtons = true
	ShowToc = true
	TocOpen = true